
symbol: A build tool for Standard ML

Usage:
  ./symbol make [make variables]
  ./symbol install [make variables]
  ./symbol clean
  ./symbol version

Make variables:
  with=(smlnj|mlton)   Which toolchain to use to build the project.
                       [default: smlnj, unless no *.cm file]
  prefix=<prefix>      Where to install the resulting binaries to.
                       [default: $HOME/.local]

--------------------------------------------------------------------------

symbol: A build tool for Standard ML

Usage:
  ./symbol make [make variables]
  ./symbol install [make variables]
  ./symbol clean
  ./symbol version

Make variables:
  with=(smlnj|mlton)   Which toolchain to use to build the project.
                       [default: smlnj, unless no *.cm file]
  prefix=<prefix>      Where to install the resulting binaries to.
                       [default: $HOME/.local]

--------------------------------------------------------------------------

symbol: A build tool for Standard ML

Usage:
  ./symbol make [make variables]
  ./symbol install [make variables]
  ./symbol clean
  ./symbol version

Make variables:
  with=(smlnj|mlton)   Which toolchain to use to build the project.
                       [default: smlnj, unless no *.cm file]
  prefix=<prefix>      Where to install the resulting binaries to.
                       [default: $HOME/.local]

--------------------------------------------------------------------------

symbol: A build tool for Standard ML

Usage:
  ./symbol make [make variables]
  ./symbol install [make variables]
  ./symbol clean
  ./symbol version

Make variables:
  with=(smlnj|mlton)   Which toolchain to use to build the project.
                       [default: smlnj, unless no *.cm file]
  prefix=<prefix>      Where to install the resulting binaries to.
                       [default: $HOME/.local]

