--- first build ----------------------------------------------------------
[ .. ] Analyzing CM dependencies...
[ .. ] Building heap image with SML/NJ...
[ .. ] Building 'TARGET' into '.symbol-work/bin'...
[ OK ] .symbol-work/bin/TARGET
--- scaffold output ------------------------------------------------------
Hello, world!
--- second build ---------------------------------------------------------
[ OK ] .symbol-work/bin/TARGET
--- install --------------------------------------------------------------
[ .. ] Building 'TARGET' into 'bin'...
[ OK ] bin/TARGET
--- install output -------------------------------------------------------
Hello, world!
