--- with=smlnj -----------------------------------------------------------
[INFO] Analyzing CM dependencies...
[INFO] Analyzing CM dependencies...
[INFO] Building heap image with SML/NJ...
Standard ML of New Jersey v110.82 [built: Tue Jan  9 20:54:24 2018]
[scanning foo.cm]
foo.cm:5.3-5.15 Error: no module exports from (foo.cm):src/main.sml
Compilation failed.
[ERR!] Building with 'smlnj' failed. See output above.
[INFO] (Debug output is in .symbol-work/debug.log)
--- debug.log ------------------------------------------------------------
...omitted...
--- with=mlton -----------------------------------------------------------
[INFO] Analyzing MLB dependencies...
[INFO] Building binary with MLton...
Error: /Users/jez/Dropbox/Documents/Programming/cli/symbol/foo/src/main.sml 2.0.
  Syntax error found at EOF.
Error: /Users/jez/Dropbox/Documents/Programming/cli/symbol/foo/src/main.sml 2.0.
  Parse error.
Error: /Users/jez/Dropbox/Documents/Programming/cli/symbol/foo/src/call-main.sml 2.26.
  Undefined structure Main.
compilation aborted: parseAndElaborate reported errors
[ERR!] Building with 'mlton' failed. See output above.
[INFO] (Debug output is in .symbol-work/debug.log)
--- debug.log ------------------------------------------------------------
./symbol log info "Building binary with MLton..." >&3
mkdir -p ".symbol-work/mlton"
mlton \
		  \
		 -prefer-abs-paths true \
		 -show-def-use foo.du \
		 -output ".symbol-work/mlton/foo" \
		 foo.mlb 2>&1 | tee .symbol-work/error.log
Error: /Users/jez/Dropbox/Documents/Programming/cli/symbol/foo/src/main.sml 2.0.
  Syntax error found at EOF.
Error: /Users/jez/Dropbox/Documents/Programming/cli/symbol/foo/src/main.sml 2.0.
  Parse error.
Error: /Users/jez/Dropbox/Documents/Programming/cli/symbol/foo/src/call-main.sml 2.26.
  Undefined structure Main.
compilation aborted: parseAndElaborate reported errors
make: *** [.symbol-work/mlton/foo] Error 1
